print("*******************************")
print("Fredy Dwi Saputra")
print("CALAS 2023")
print("*******************************")
print('\n')
print("RUMUS PERSEGI PANJANG")
print("Ikuti instruksi berikut untuk menghitung Luas dan Keliling Persegi Panjang")
x = int(input("Masukkan besar nilai Panjang: "))
y = int(input("Masukkan besar nilai Lebar: "))
L_Psgp= int(x*y)
K_Psgp= int(2*(x+y))
print("Luas Persegi Panjang adalah: ", L_Psgp)
print("Keliling Persegi Panjang adalah: ", K_Psgp)